services:
  db:
    image: mysql:8.0
    container_name: iot_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: smart_store
      MYSQL_USER: iot_user
      MYSQL_PASSWORD: iot_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/Iot_Database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: